import type { ThemeConfig } from 'antd';

export const themeConfig: ThemeConfig = {
  token: {
    colorPrimary: '#1677ff',
    colorSuccess: '#52c41a',
    colorWarning: '#faad14',
    colorError: '#ff4d4f',
    colorInfo: '#1677ff',
    colorTextBase: '#262626',
    colorBgBase: '#ffffff',
    borderRadius: 6,
    wireframe: false,
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
    fontSize: 14,
    lineWidth: 1,
    controlHeight: 32,
  },
  components: {
    Layout: {
      headerBg: '#ffffff',
      headerColor: '#262626',
      siderBg: '#ffffff',
      triggerBg: '#f5f5f5',
      triggerColor: '#262626',
      bodyBg: '#f5f5f5',
    },
    Menu: {
      itemBg: 'transparent',
      itemColor: '#595959',
      itemActiveBg: '#e6f4ff',
      itemSelectedBg: '#e6f4ff',
      itemSelectedColor: '#1677ff',
      horizontalItemSelectedColor: '#1677ff',
      horizontalItemHoverColor: '#1677ff',
      itemHoverColor: '#1677ff',
    },
    Card: {
      borderRadiusLG: 8,
      boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.03), 0 1px 6px -1px rgba(0, 0, 0, 0.02), 0 2px 4px 0 rgba(0, 0, 0, 0.02)',
    },
    Button: {
      borderRadius: 6,
      controlHeight: 32,
      controlHeightLG: 40,
      controlHeightSM: 24,
      colorPrimary: '#1677ff',
      colorPrimaryHover: '#4096ff',
      colorPrimaryActive: '#0958d9',
      colorText: '#262626',
      colorBgContainer: '#ffffff',
      colorBorder: '#d9d9d9',
      colorTextDisabled: '#bfbfbf',
      colorBgContainerDisabled: '#f5f5f5',
    },
    Dropdown: {
      borderRadius: 6,
      colorBgElevated: '#ffffff',
      colorText: '#262626',
      colorBgTextHover: '#f5f5f5',
      controlItemBgActive: '#e6f4ff',
      controlItemBgHover: '#f5f5f5',
    },
    Input: {
      borderRadius: 6,
      controlHeight: 32,
    },
    Table: {
      borderColor: '#f0f0f0',
      headerBg: '#fafafa',
      headerColor: '#262626',
      rowHoverBg: '#fafafa',
    },
  },
};

export const darkThemeConfig: ThemeConfig = {
  token: {
    colorPrimary: '#1677ff',
    colorSuccess: '#52c41a',
    colorWarning: '#faad14',
    colorError: '#ff4d4f',
    colorInfo: '#1677ff',
    colorTextBase: '#ffffff',
    colorBgBase: '#141414',
    borderRadius: 6,
    wireframe: false,
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
    fontSize: 14,
    lineWidth: 1,
    controlHeight: 32,
  },
  components: {
    Layout: {
      headerBg: '#141414',
      headerColor: '#ffffff',
      siderBg: '#141414',
      triggerBg: '#262626',
      triggerColor: '#ffffff',
      bodyBg: '#0f0f0f',
    },
    Menu: {
      itemBg: 'transparent',
      itemColor: '#d9d9d9',
      itemActiveBg: '#111b26',
      itemSelectedBg: '#111b26',
      itemSelectedColor: '#1677ff',
      horizontalItemSelectedColor: '#1677ff',
      horizontalItemHoverColor: '#1677ff',
      itemHoverColor: '#1677ff',
    },
    Card: {
      borderRadiusLG: 8,
      boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.45), 0 1px 6px -1px rgba(0, 0, 0, 0.3), 0 2px 4px 0 rgba(0, 0, 0, 0.3)',
    },
    Button: {
      borderRadius: 6,
      controlHeight: 32,
      controlHeightLG: 40,
      controlHeightSM: 24,
      colorPrimary: '#1677ff',
      colorPrimaryHover: '#4096ff',
      colorPrimaryActive: '#0958d9',
      colorText: '#ffffff',
      colorBgContainer: '#1677ff',
      colorBorder: '#1677ff',
      colorTextDisabled: '#bfbfbf',
      colorBgContainerDisabled: '#262626',
    },
    Dropdown: {
      borderRadius: 6,
      colorBgElevated: '#141414',
      colorText: '#d9d9d9',
      colorBgTextHover: '#262626',
      controlItemBgActive: '#111b26',
      controlItemBgHover: '#262626',
    },
    Input: {
      borderRadius: 6,
      controlHeight: 32,
    },
    Table: {
      borderColor: '#303030',
      headerBg: '#262626',
      headerColor: '#ffffff',
      rowHoverBg: '#262626',
    },
  },
};